### ISSUE TITLE
Runtime error : Current match not defined

### ISSUE THREAD

**Issue by yueisme** [akiver/cs-demo-manager#852] opened 2024-05-29 10:34 UTC
### Describe the bug

Runtime error screen when open a match, I copy error log in Additional context. re-analyze demo can't reproduce.

### Demo links

g2-vs-vitality-m1-dust2.dem from https://r2-demos.hltv.org/demos/105216/iem-dallas-2024-g2-vs-vitality-bo3-OgMAlM_OpDjWEZQmgmrVeh.rar

### Steps to reproduce

1. start csdm
2. put a demo file in csdm demo folder
3. refresh demos page
4. analyze demo
5. open that analyzed match on matchs page
6. csdm tell me error happend

### Expected behavior

dont crash

### How often does this bug happen?

Only once

### Log file

upload after if need.

### Environment information

Version: 3.5.3
OS: win32 x64 10.0.22631
Electron: 30.0.3
Chrome: 124.0.6367.119

### Additional context

```
Error: Current match not defined
    at useCurrentMatch$1 (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:215:35976)
    at MatchOverview (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:237:4442)
    at Nh (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:38:18176)
    at cj (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:40:3212)
    at Vk (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:40:46762)
    at Uk (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:40:41468)
    at Tk (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:40:41391)
    at Ik (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:40:41234)
    at Nk (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:40:37419)
    at Ek (file:///C:/Users/yue/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-CzsoD8Rc.js:40:38239)
```

**Comment by akiver** [comment] 2024-05-29 20:13
Do you have more information on how to reproduce the issue?

**Comment by akiver** [comment] 2024-06-03 22:02
I'm closing it since it's hard to reproduce the problem - feel free to re-open if you find a way to reproduce the issue.

**Closed by akiver** 2024-06-03 22:02 UTC
Labels: bug, need-repro
