### ISSUE TITLE
Watch player's highlights focus of game are wrong at first kill.

### ISSUE THREAD

**Issue by yueisme** [akiver/cs-demo-manager#833] opened 2024-05-14 11:41 UTC
### Describe the bug

same as title

### Steps to reproduce

1. pick a match and a player
2. watch highlight and choose enemy's POV
3. use player's POV watch highlight again
4. the first kill focus are wrong

### Expected behavior

first kill focus on player

### How often does this bug happen?

Every time

### Environment information

Version: 3.5.3
OS: win32 x64 10.0.22631
Electron: 30.0.3
Chrome: 124.0.6367.119
Last database migrations:
v2 - 2024-04-13T22:50:22.363Z

**Comment by akiver** [comment] 2024-05-14 21:12
Duplicate of https://github.com/akiver/cs-demo-manager/issues/775
Could you complete the other issue if you have more information to reproduce the issue?
It looks like it's a CS2 bug with non-valve demos and a workaround is to use a 2nd Steam account.

**Closed by akiver** 2024-05-14 21:12 UTC
