### ISSUE TITLE
Raw files not found or Wav files not found

### ISSUE THREAD

**Issue by lwimanutd** [akiver/cs-demo-manager#712] opened 2023-12-19 05:11 UTC
### Describe the bug

Using cs demo mangager to create videos prompts "Raw files not found" when generating

### Demo links

all file

### Steps to reproduce

![20231219125243](https://github.com/akiver/cs-demo-manager/assets/61498986/248fd29d-dda2-402f-8dc0-3e19b07a46f2)

### Expected behavior

When the game exits, I can see the generated tga file in the raw directory, and then an error message appears, and the file is automatically deleted.

### How often does this bug happen?

Every time

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/13711448/csdm.log)

### Environment information

Version: 3.0.6
操作系统：win10 x64 19045.2311 pro

**Comment by akiver** [comment] 2023-12-19 20:01
I can't reproduce the issue.  
Could you please upload the demo and give more details about your sequences and options? (raw files location, output folder location...)

**Comment by BinaryChop** [comment] 2023-12-20 18:10
Same issue. these are my settings. HLAE and FFMPEG are installed in the default locations, so I just installed them via demomanager.  Raw files folder was preset. Output folder was set by me.  Ticked all variations of the 3 left boxes but still got the same error after running the task. 

![Screenshot_207](https://github.com/akiver/cs-demo-manager/assets/101369051/ff0db68e-d21e-4104-ae95-49f023ea096c)

**Comment by loganripplinger** [comment] 2023-12-21 20:11
I also observed that using "Generate players kill sequences" caused the `Raw files not found` error. However I found that if you delete some of the generated sequences it will successfully finish. I don't remember the exact amount but around 10 total sequences remaining sounds right.

**Comment by OldGodShen** [comment] 2023-12-23 19:09
I also encountered this problem

**Comment by akiver** [comment] 2023-12-23 21:29
Thank you for the help in understanding the issue!

If the initial issue from @lwimanutd is the same, it should be fixed in the next release.  
There was a regression introduced in v3.0.6 that prevents to generate more than 9 sequences and should fixed with https://github.com/akiver/cs-demo-manager/commit/0993b5d5196db2da51c90771c22f8f1d1774812c

**Closed** 2023-12-31 01:37 UTC
Labels: bug, next-release-resolved
