### ISSUE TITLE
psql threads accumulating

### ISSUE THREAD

**Issue by ClementCariou** [akiver/cs-demo-manager#890] opened 2024-07-03 23:30 UTC
### Describe the bug

I got psql threads accumulating when I lose db connection. I also have to restart the Postgres server from time to time.
![image](https://github.com/akiver/cs-demo-manager/assets/37800288/20b66b8b-b444-4a2a-8d8f-fc46bec75da5)

### Steps to reproduce

1. Start the application
2. Download and analyse demos
3. Loose database connection
4. Close the application
5. `psql` threads are still running

### Expected behavior

I would expect the psql threads to be killed after processing and after closing the application.

### How often does this bug happen?

Often

### Log file

[csdm.log](https://github.com/user-attachments/files/16091525/csdm.log)
[postgresql-json.log](https://github.com/user-attachments/files/16091602/fa39d3311d4a0efc27ac169abd010f32de6f843ba3b122fe5a0bbb3358216166-json.log)

### Environment information

- Version 3.7.0
- OS Windows 23H2

**Comment by akiver** [comment] 2024-07-06 13:31
I can't reproduce the issue
1. are you using a remote database?
2. your log shows PostgreSQL v14, while it may work it's recommended to use the v16
3. how many matches do you have?
4. how do you "lose your db connection"?

**Comment by ClementCariou** [comment] 2024-07-06 14:47
1. are you using a remote database?
  => yes, hosted on my local network
2. your log shows PostgreSQL v14, while it may work it's recommended to use the v16
  => I've reproduced with PostgreSQL v16
3. how many matches do you have?
  => 1950 matches
4. how do you "lose your db connection"?
  => I stop the database

I reproduced it on [video](https://github.com/akiver/cs-demo-manager/assets/37800288/fb1d72fe-4e11-46a8-aa61-b6882ca1d2f9).
> Notice in real life I don't manually try to reconnect to the database. I get several psql threads running for no reason while using my computer normally.

**Comment by akiver** [comment] 2024-07-06 15:44
thanks!
it will be fixed in the next release

**Closed** 2024-07-14 11:42 UTC
Labels: bug, next-release-resolved
