### ISSUE TITLE
Demo Playback Issue - Can't Focus on One Player

### ISSUE THREAD

**Issue by Bubbl666** [akiver/cs-demo-manager#843] opened 2024-05-20 19:35 UTC
### What problem is this solving

Hello Akiver,

I recently noticed an issue when watching demos by rounds. The camera often fails to focus on me and instead shifts to other players. For example, in some rounds where I die, the console shows spec_lock_to_accountid "my steam ID". However, in other rounds, it shows spec_lock_to_accountid 0, causing me to lose my view.

Is this due to the latest CS2 update? I believe this is a valuable feature from CSGO that should be retained in the CS2 demo manager.

Thank you, and all the best!

### Proposed solution

Is there any way to solve this problem so the camera can stay focused on the selected player?

**Comment by akiver** [comment] 2024-05-22 17:59
Hi,

This is probably the same issue as https://github.com/akiver/cs-demo-manager/issues/775.
It **could be** a CS2 bug and as a workaround you can use a secondary Steam account (see [#775](https://github.com/akiver/cs-demo-manager/issues/775)).

> However, in other rounds, it shows spec_lock_to_accountid 0, causing me to lose my view.

1. It happens when you watch players highlights?
2. Is it a valve demo? It has been reported that it happens only with non valve demos.
3. Could you upload an affected demo and steps to reproduce the issue

Thanks

**Comment by Bubbl666** [comment] 2024-05-29 18:48
Hi Akiver,

Just a heads up, I'm still experiencing issues with maintaining focus on a single player; it remains random. I've also tried watching some HLTV and FACEIT demos (professional demos, not mine). Also, this issue didn't occur before the last update. Could it be related to this update: feat(playback): allow focusing camera on other players after initial focus https://github.com/akiver/cs-demo-manager/issues/813?

Sometimes, during certain rounds, I can switch to another player's view even though I've selected to watch just one player's view.
Thanks!

**Comment by akiver** [comment] 2024-05-29 20:12
> Sometimes, during certain rounds, I can switch to another player's view even though I've selected to watch just one player's view.

Since v3.5.3 the camera is unlocked a few seconds after calling `spec_lock_to_accountid xxx`.
It allows users to focus on other players if they want to and mimic the CSGO behavior (that's the goal of https://github.com/akiver/cs-demo-manager/issues/813).

**Comment by akiver** [comment] 2024-05-29 21:14
Closing for https://github.com/akiver/cs-demo-manager/issues/775

**Closed by akiver** 2024-05-29 21:14 UTC
Labels: bug, duplicate
