### ISSUE TITLE
Error when tyrying analyze a demo

### ISSUE THREAD

**Issue by zatmania** [akiver/cs-demo-manager#700] opened 2023-12-14 20:09 UTC
### Describe the bug

unknown grenade model 8528019637059176743unknown grenade model 5178294830165861005Grenade nil in decoy start event
Grenade nil in decoy start event
Command failed: psql -c "\copy matches(checksum,game,demo_path,name,date,source,type,map_name,server_name,client_name,tick_count,tickrate,framerate,duration,network_protocol,build_number,game_type,game_mode,game_mode_str,is_ranked,kill_count,assist_count,death_count,shot_count,winner_name,winner_side,overtime_count,max_rounds,has_vac_live_ban) FROM 'C:\Users\zat\AppData\Local\Temp\cs-demo-manager\match730_003655703023633563904_0252594089_195_match.csv' CSV DELIMITER ','" "postgresql://*****:*****@*****:****/csdm"
ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « matches_pkey »
D�TAIL : La clé « (checksum)=(fe71d27d9cd964d) » existe déjà.
CONTEXTE : COPY matches, ligne 1

### Demo links

match730_003655703023633563904_0252594089_195

### Steps to reproduce

Only launch app

### Expected behavior

I just want to analyze the demo

### How often does this bug happen?

None

### Environment information

Windows 11 pro

**Comment by akiver** [comment] 2023-12-14 21:01
Duplicate of #657 - closing this one.

Based on the logs, the problem is that the same demo is being added twice into the database when it should not.
Please comment on the other issue with steps to reproduce the issue and links to download the demos (screenshots/videos are welcome).
If you can find duplicate demos on your filesystem, that would help too.
You can search for a demo/match by checksum by copying/pasting the checksum `fe71d27d9cd964d` in the Filter input text at the top-right.

**Closed by akiver** 2023-12-14 21:01 UTC
