### ISSUE TITLE
Raw files not found

### ISSUE THREAD

**Issue by kmesong** [akiver/cs-demo-manager#763] opened 2024-02-13 10:22 UTC
### Describe the bug

When I try to generate a video and if I keep the game on the foreground, it immediately closes and I have the error Raw files not found. If I leave it in the background, then it can generate a video but at the risk of not being in the right view (as 
 described in the FAQ). It happens with every demos (even before the big patch).

### Steps to reproduce

1. Go to a demo
2. Select video and generate kill sequences
3. Select Generate button
4. Game is launching on the foreground and closes.
5. Raw files not found on the application

### Expected behavior

1. Go to a demo
2. Select video and generate kill sequences
3. Select Generate button
4. Game is launching on the foreground
5. Video is generated

### How often does this bug happen?

Every time

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/14259741/csdm.log)

### Environment information

Version: 3.2.3
OS: win32 x64 10.0.22631
Electron: 28.2.2
Chrome: 120.0.6099.276
Last database migrations:
v1 - 2024-01-29T15:38:50.402Z

**Comment by akiver** [comment] 2024-02-13 18:24
I can't reproduce the issue. Could you upload the demo please?

Did you try to watch the demo directly from the game? See [this doc](https://cs-demo-manager.com/docs/faq/playback#cs2-demo-playback-doesnt-start-or-crashes) for details.  
If the game crashes when the playback starts, it may be due to a demo/game bug.

**Comment by kmesong** [comment] 2024-02-13 18:36
Here is a demo: https://www.mediafire.com/file/s19a9wnvlygbpru/match730_003667426248537145557_1073661515_377.dem/file

I can watch the demo directly from the game without any issues.

**Comment by akiver** [comment] 2024-02-13 18:51
Just tried without problems, could you send a screenshot of your sequences?

I tried with a single sequence:
![f](https://github.com/akiver/cs-demo-manager/assets/1842524/488385d9-2046-47dd-a2d7-630e96afd3cd)

**Comment by kmesong** [comment] 2024-02-13 19:25
I used the Generate player's kill sequence functionality:

![Screenshot 2024-02-13 200029](https://github.com/akiver/cs-demo-manager/assets/635736/901437d1-4af6-45a1-a19d-7788d0815089)
![Screenshot 2024-02-13 200013](https://github.com/akiver/cs-demo-manager/assets/635736/18d3a8b9-32ad-42ad-984a-7dd312f65aef)

If I delete all but the first one, it seems to be working but the sequence is too short (not going until the end).

**Comment by akiver** [comment] 2024-02-13 20:51
I still can't reproduce the problem :/  
I generated kills of the player "KM" based on your screenshot and I don't have any errors - the video is generated and contains all kills.

I added some logs to try to understand the problem, it will be in the next version.
In the meantime you could:
- Make sure you have enough disk space on the drive where **CS2 is installed**, see [this CS2 only warning](https://cs-demo-manager.com/docs/guides/video#raw-files-folder)
- Delete any temporary files in your `D:/Videos` folder (tga, wav files)

**Comment by kmesong** [comment] 2024-02-14 12:17
I have 80Gb free on my drive where CS2 is installed, 220 on my D: drive. The estimated usage is 8GB so I don't think it is the issue.
I have done some more testing:

- If I generate for just one sequence, it is working.
- If I generate for the same previous sequence and I add one more, I have the error.
- If I only generate the second sequence alone, it is working.
- Once the two sequences have been generate individually, I can do both of them at the same time without error but only once!
If I generate again the same two sequences, I have the error again.

**Comment by akiver** [comment] 2024-02-16 01:31
Could you try with v3.3.0 and upload the logs file please?

**Comment by kmesong** [comment] 2024-02-16 10:48
I still have the issue with v3.3.0.
[csdm.log](https://github.com/akiver/cs-demo-manager/files/14309896/csdm.log)

**Comment by akiver** [comment] 2024-02-22 22:54
I still can't reproduce the problem.

> Fri, 16 Feb 2024 10:43:16 GMT | ERROR | server | TGA files not found for sequence 2-sequence

I think there are 2 possible reasons:
- The files of the sequence 2 were moved at the same time as files of the sequence 1
- The game didn't generate images

I added some logs to try to understand, could you please try with the new version and upload the log file if it still doesn't work?

**Comment by kmesong** [comment] 2024-02-23 13:51
Your change seems to be enough. I did not have the error at all now.
I started playing on FaceIT now, is there a known issue where the POV is not on the selected user on faceit demos? For Valve demos, it seems to be okay though.

**Comment by akiver** [comment] 2024-02-26 21:53
Cool! 
About the POV it could be the same as https://github.com/akiver/cs-demo-manager/issues/775

**Closed by akiver** 2024-02-26 21:53 UTC
Labels: reply-needed, need-repro

**Comment by aserighelli** [comment] 2024-06-16 01:27
Sorry to bump an old topic, dont know if i sould create a new one or not.

I am having this error on version 3.6.3 when i try to generate a video of round 16 of the below demo.
https://www.mediafire.com/file/0v6z32sljiharwo/match730_003690266270436950035_2060405378_201.dem/file

All i am getting in the log file is 

`Sun, 16 Jun 2024 01:17:52 GMT | LOG | server | Starting HLAE with command "C:\Users\aseri\.csdm\hlae\hlae.exe" -noGui -autoStart -afxDisableSteamStorage -customLoader -hookDllPath "C:\Users\aseri\.csdm\hlae\x64\AfxHookSource2.dll" -programPath "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe" -cmdLine "-insecure -novid +playdemo \"C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\replays\match730_003690266270436950035_2060405378_201.dem\" -width 1024 -height 768 -sw"
Sun, 16 Jun 2024 01:17:54 GMT | LOG | server | HLAE exited with code 0
Sun, 16 Jun 2024 01:18:04 GMT | ERROR | server | Recording folder does not exist C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\csdm\movie
Sun, 16 Jun 2024 01:18:04 GMT | LOG | renderer | WS:: message with name "videos-generation-error" received from server
Sun, 16 Jun 2024 01:18:04 GMT | ERROR | server | Error while generating videos
Sun, 16 Jun 2024 01:18:04 GMT | ERROR | server | Error: Raw files not found
    at iVe (C:\Users\aseri\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\sequences\move-sequences-raw-files.ts:35:11)
    at oVe (C:\Users\aseri\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\generate-videos.ts:273:5)
    at sVe (C:\Users\aseri\AppData\Local\Programs\cs-demo-manager\resources\src\server\handlers\renderer-process\video\generate-videos-handler.ts:56:5)
    at t.onRendererProcessSocketMessage (C:\Users\aseri\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:177:26)
`

**Comment by ehwhattaugonnado** [comment] 2024-09-20 21:29
After having this issue, stumbling across this issue, and testing some things out I think I have a pretty good idea what's going on. I think it is caused by the raw files not being copied fast enough/some other issue in the copying. It only happens when I'm telling it to move the raw files to a different drive and recording at a low resolution. Even then it only happens with short sequences. 

Generate kill video of a 7 kill game at 720p 30 raw files not found. Same sequence at 1080p60 works. I'm moving from nvme to nvme so it's copying quick.

Your idea that the files for multiple sequences are being moved at the same time seems likely. It would only happen with very small files when the raw output folder is on a different drive than the game.

> I still can't reproduce the problem.
> 
> > Fri, 16 Feb 2024 10:43:16 GMT | ERROR | server | TGA files not found for sequence 2-sequence
> 
> I think there are 2 possible reasons:
> 
> * The files of the sequence 2 were moved at the same time as files of the sequence 1
> * The game didn't generate images
> 
> I added some logs to try to understand, could you please try with the new version and upload the log file if it still doesn't work?

**Comment by akiver** [comment] 2024-09-24 18:30
Thanks all for the help! I managed to reproduce the issue.

I will update the status in https://github.com/akiver/cs-demo-manager/issues/920 as this issue is not the same problem.
